site_name: Kitchen Sink Full of Cravings
site_author: Cookiecuttermonster
site_description: Cookies!

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
